apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certificate-generator
  namespace: ${service-namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: certificate-generator
subjects:
- kind: ServiceAccount
  name: certificate-generator
  namespace: kube-system
