kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: certificate-generator
  namespace: ${service-namespace}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
      - get
